name: Deploy to EC2

on:
  push:
    branches:
      - main
      - aws_cd_branch
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy to EC2
        run: |
          echo "Starting deployment..."
          rsync -avz --exclude '.git' \
                     --exclude 'node_modules' \
                     -e "ssh -i ~/.ssh/id_rsa" \
                     ./ "ec2-user@${{ secrets.EC2_HOST }}:~/registry/"
          
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} "
            # Setup Node.js
            export NVM_DIR=\$HOME/.nvm
            [ -s \$NVM_DIR/nvm.sh ] && \. \$NVM_DIR/nvm.sh

            cd ~/registry

            # Clear npm cache and remove existing node_modules
            npm cache clean --force
            rm -rf node_modules package-lock.json

            # Install dependencies including TypeScript
            npm install
            npm install -g typescript

            # Verify TypeScript installation
            which tsc
            tsc --version

            # Initialize TypeScript if needed
            if [ ! -f tsconfig.json ]; then
              tsc --init
            fi

            # Make run script executable
            chmod +x run
            
            # Run installation script
            ./run install
          "