name: Deploy to EC2

on:
  push:
    branches:
      - aws_cd_dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix file permissions
        run: |
          chmod -R 755 .
          git config --global --add safe.directory '*'

      - name: Set executable permissions for ./run
        run: chmod +x run

      - name: Create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "LOG_FILE=/LOGS/log_file.txt" >> .env
          echo "LOG_LEVEL=2" >> .env # Add other environment variables as needed

      - name: Setup Source .env file
        run: set -a; source .env; set +a

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "~/backend"
          strip_components: 1
          rm: true
          overwrite: true
          timeout: 120s

      - name: Install Dependencies and Configure
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/backend
            
            # Install dependencies
            npm install typescript --save-dev
            npm install express @types/express
            npm install
            
            # Initialize TypeScript configuration if not exists
            ./node_modules/.bin/tsc --init || true
            
            set -a
            source .env
            set +a
            ./run install

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Verifying deployment..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/backend
            ls -la
            node --version
            npm --version
            ./node_modules/.bin/tsc --version
            # Verify express installation
            npm list express
