# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - aws_cd_dev

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
        
#       - name: Create SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
#           chmod 600 ~/.ssh/deploy_key
          
#       - name: Prepare backend directory
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: 443
#           script: |
#             echo "Cleaning up old backend directory..."
#             rm -rf ~/backend
#             echo "Creating fresh backend directory..."
#             mkdir -p ~/backend

#       - name: Copy files to EC2
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: 443
#           source: "."
#           target: "~/backend"
#           strip_components: 1
#           use_insecure_cipher: true
#           overwrite: true

#       - name: Verify deployment
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: 443
#           script: |
#             echo "Deployment started"
#             cd ~/backend
#             echo "Files in backend directory:"
#             ls -la
#             echo "Deployment completed"

on:
  push:
    branches:
      - aws_cd_dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ec2-34-205-19-248.compute-1.amazonaws.com  # Use public DNS
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "~/backend"
          strip_components: 1
          overwrite: true
          use_insecure_cipher: true
          debug: true
          timeout: 120s

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ec2-34-205-19-248.compute-1.amazonaws.com  # Use public DNS
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Verifying deployment..."
            ls -la ~/backend