name: Deploy to EC2

on:
  push:
    branches:
      - aws_cd_dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment archive
        run: |
          tar --exclude='.git' --exclude='.github' -czf deploy.tar.gz .

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 443
          source: "deploy.tar.gz"
          target: "~/"
          strip_components: 0

      - name: Extract files on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 443
          script: |
            rm -rf ~/backend
            mkdir -p ~/backend
            tar -xzf ~/deploy.tar.gz -C ~/backend
            rm ~/deploy.tar.gz
