# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - aws_cd_dev

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Fix file permissions
#         run: |
#           chmod -R 755 .
#           git config --global --add safe.directory '*'

#       - name: Deploy to EC2
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: 22
#           source: "."
#           target: "~/backend"
#           strip_components: 1
#           rm: true
#           overwrite: true
#           timeout: 120s

#       - name: Install and Configure
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: 22
#           script: |
#             cd ~/backend
#             set -a
#             source .env
#             set +a
#             ./run install

#       - name: Verify Deployment
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: 22
#           script: |
#             echo "Verifying deployment..."
#             ls -la ~/backend

name: Deploy to EC2

on:
  push:
    branches:
      - aws_cd_dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix file permissions
        run: |
          chmod -R 755 .
          git config --global --add safe.directory '*'

      - name: Set executable permissions for ./run
        run: chmod +x run

      - name: Create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "LOG_FILE=/LOGS/log_file.txt" >> .env
          echo "LOG_LEVEL=2" >> .env # Add other environment variables as needed

      - name: Setup Source .env file
        run: set -a; source .env; set +a

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "~/backend"
          strip_components: 1
          rm: true
          overwrite: true
          timeout: 120s

      - name: Install Dependencies and Configure
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Install Node.js and npm if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Install TypeScript globally if not present
            if ! command -v tsc &> /dev/null; then
              sudo npm install -g typescript
            fi
            
            cd ~/backend
            set -a
            source .env
            set +a
            ./run install

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Verifying deployment..."
            ls -la ~/backend
            node --version
            npm --version
            tsc --version
