name: Deploy to EC2
on:
  push:
    branches:
      - aws_cd_dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix file permissions
        run: |
          chmod -R 755 .
          git config --global --add safe.directory '*'

      - name: Set executable permissions for ./run
        run: chmod +x run

      - name: Create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "LOG_FILE=LOGS/log_file.txt" >> .env
          echo "LOG_LEVEL=2" >> .env
      
      - name: Debug EC2_HOST
        run: echo "EC2_HOST is ${{ secrets.EC2_HOST }}"

      - name: Deploy to EC2 (scp)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "~/backend"
          strip_components: 1
          rm: true
          overwrite: true
          timeout: 180s
          debug: true

      - name: Install and Setup
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          debug: true
          script: |
            # Ensure that nvm is installed and sourced correctly
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            source ~/.bashrc
            nvm install 18
            cd ~/backend
            mkdir -p LOGS
            touch LOGS/log_file.txt
            npm ci --no-fund --no-audit --loglevel=error
            ./run install

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          debug: true
          script: |
            source ~/.bashrc
            cd ~/backend
            node --version
            npm --version