on:
  push:
    branches:
      - aws_cd_dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ec2-34-205-19-248.compute-1.amazonaws.com  # Use public DNS
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "~/backend"
          strip_components: 1
          overwrite: true
          use_insecure_cipher: true
          debug: true
          timeout: 120s

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ec2-34-205-19-248.compute-1.amazonaws.com  # Use public DNS
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Verifying deployment..."
            ls -la ~/backend