name: Push-to-EC2

# Define when this workflow will run
on:
  # Trigger on push to specific branches
  push:
    branches: [ "main" ]  # Replace with your branch name
  
  # Allow manual triggers
  workflow_dispatch:

# Job definition
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Setup SSH
      run: |
        echo "Setting up SSH..."
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" > ~/.ssh/config
        chmod 600 ~/.ssh/config
        echo "SSH setup complete"

    - name: Deploy to EC2
      run: |
        echo "Starting deployment to ${{ secrets.EC2_HOST }}..."
        rsync -avz --exclude '.git' ./ ec2-user@${{ secrets.EC2_HOST }}:~/registry/
        ssh ec2-user@${{ secrets.EC2_HOST }} 'cd ~/registry && chmod +x run && ./run install'