# .github/workflows/deploy.yml 
name: Deploy Custom Registry

on:
  push:
    branches: [ aws_cd_dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    
    - name: Get EC2 Instance IP
      id: get-ip
      run: |
        IP=$(aws ec2 describe-instances \
          --filters "Name=tag:aws:cloudformation:stack-name,Values=CustomRegistry" \
          --query 'Reservations[].Instances[].PublicIpAddress' \
          --output text)
        echo "instance_ip=$IP" >> $GITHUB_OUTPUT

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ steps.get-ip.outputs.instance_ip }} >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: |
        # Copy code to EC2
        rsync -avz --exclude '.git' ./ ec2-user@${{ steps.get-ip.outputs.instance_ip }}:~/registry/
        
        # Run install
        ssh ec2-user@${{ steps.get-ip.outputs.instance_ip }} 'cd ~/registry && chmod +x run && ./run install'