name: Deploy to EC2 Frontend
on:
  pull_request:
    types: [closed]
    branches: [ dev_dirs ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.ACME_PEM }}
          HOST: 3.87.4.91
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} 'mkdir -p ~/frontend'
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./frontend/* ${USER}@${HOST}:~/frontend/
          rm -f private_key.pem