name: Pull Request Workflow

on:
    push:
        branches:
            - aws_cd_branch
    pull_request:
        branches:
            - aws_cd_branch

# linter for the cloudformation template
jobs:
    cloudformation-linter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install cfn-lint
              uses: ScottBrenner/cfn-lint-action@v2
              with:
                    command: cfn-lint -t ./cfn-template.yaml 